stages:
  - build

build-fake-sensors:
  image: docker:latest
  stage: build
  script:
    - echo "Building Fake Sensor Image"
    - docker build -t iotssg5ws2020/fake-sensor:$CI_COMMIT_REF_SLUG ./fake-sensor/
    - docker push iotssg5ws2020/fake-sensor:$CI_COMMIT_REF_SLUG

build-data-filter:
  image: docker:latest
  stage: build
  script:
    - echo "Building Data Filter Image"
    - docker build -t iotssg5ws2020/data-filter:$CI_COMMIT_REF_SLUG ./data-filter/
    - docker push iotssg5ws2020/data-filter:$CI_COMMIT_REF_SLUG

build-blockchain-publisher:
  image: docker:latest
  stage: build
  script:
    - echo "Building Blockchain Publisher Image"
    - docker build -t iotssg5ws2020/blockchain-publisher:$CI_COMMIT_REF_SLUG ./data-filter/
    - docker push iotssg5ws2020/blockchain-publisher:$CI_COMMIT_REF_SLUG