version: "3"
services:
  message-broker:
    image: eclipse-mosquitto
    hostname: broker
    networks:
      - default
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      
  blockchain-publisher:
    build:
      context: ./blockchain-publisher
    environment:
      - MQTT_HOST=message-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=mytopic
      - BLOCKCHAIN_HOST=ganache:8545
    depends_on:
      - message-broker
      - ganache
  
  ganache:
    image: trufflesuite/ganache-cli
    expose:
      - 8545
    ports:
      - 8545:8545    

